[workspace]
resolver = "2"
members = [
    "hello_channel",
    "hello_compute",
    "hello_crossterm",
    "hello_customized_vec",
    "hello_factorial",
    "hello_file_watcher",
    "hello_grpc",
    "hello_permutation",
    "hello_progress_bar",
    "hello_self_response",
    "hello_slice",
    "hello_mesh_shader",
    "hello_tauri/src-tauri",
    "hello_tokio_stream",
    "hello_world",
    "hello_vulkan_on_ash",
    "hello_random",
    "hello_rapier",
    "hello_regex",
    "hello_winit",
]

[workspace.dependencies]
ash = { version = "0.38.0", default-features = false, features = [
    "linked",
    "debug",
    "std",
] }
bytemuck = "*"
naga = { version = "25", features = ["glsl-in", "spv-out", "wgsl-out"]}
notify = "*"
tonic = "0.5"
tonic-build = "0.5"
tokio = { version = "1", features = ["full"] }
tokio-stream = "*"
prost = "0.8.0"
regex = "*"
winit = { version = "0.30" }
wgpu = { version = "22.1.0", features = ["spirv"] }
