[workspace]
resolver = "2"
members = [
  "hello_grpc",
  "hello_self_response",
  "hello_world"
]

[workspace.dependencies]
tonic = "0.5"
tonic-build = "0.5"
tokio = { version = "1", features = ["full"] }
prost = "0.8.0"

