[package]
name = "hello_compute"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio.workspace = true	
wgpu.workspace = true
bytemuck.workspace = true

[build-dependencies]
shaderc = "0.7"
