[package]
name = "hello_self_response"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic.workspace = true
tokio.workspace = true
prost.workspace = true

[build-dependencies]
tonic-build.workspace = true
